# Generated by Django 3.2.5 on 2021-09-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210915_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Language',
            new_name='language',
        ),
    ]
